apiVersion: v1
kind: Pod
metadata:
  name: kafkat
spec:
  containers:
  - name: kafkat
    image: bitnami/kafka:2.4.0
    command:
      - ./entrypoint.sh
    args:
      - /bin/sleep
      - "10800"
    imagePullPolicy: IfNotPresent
    env:
      - name: KAFKA_ENV
        value: 'Forno'
  restartPolicy: Always
